spring.datasource.url=jdbc:h2:file:./data/compia
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=emails.teste.dev@gmail.com
spring.mail.password=kcxu uyzv gkje mwmh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

melhorenvio.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NTYiLCJqdGkiOiIxMGRjN2E1ODAyOTExNmIzMWRkYjQ2NjQ3NzNkNmIxNDUxMWNlMDM4NWZhMWEwZTA5ZTk0OWYwZDk3ZGRlY2QyYWIxZmY2NjU3MmI2ZTk2OCIsImlhdCI6MTc3MzQzMDE2Mi45MDMzMSwibmJmIjoxNzczNDMwMTYyLjkwMzMxMywiZXhwIjoxODA0OTY2MTYyLjg5MzIyLCJzdWIiOiJhMTQ5NDk3Zi1lNGZjLTQ2OGMtODU0OC0yMzA0YzMzYTc5YmYiLCJzY29wZXMiOlsic2hpcHBpbmctY2FsY3VsYXRlIl19.U3skTjl02rtdBhiSNu1xOL77P0-KtKXGNibtEUk08GXB6v8V4fGMlc-OuuRfHXy54FgkFFWoVJWRwtKMlFBMNu9fIFfwA70MeAer-0r-J9SoNTs0FCW0s3yQqowzTyW02qWCtrzDHJ1BgNp5-Q5KXCbMBosLeDTVjInYYlV6P4A5eUKBHHxdFVhLJrwE9UXBMSZ6G0sBY88nr94ovu6mYA6lmfmh6fW4b5CDgL2dwrsQ_3P9ph1mANE-sQFkhjXlSZbad0rPULPuo9WOXMPCmhGcsxaekPX9Mvaptefp1ecoPAyRVbynUVywge6MZrqgpX2oLHdRyOtHmMhMuMYl4dTGRfPxBHK8eA1exLfOiDtJLd8XH7uDuplTgmfHbTKXew_JbHkkcJHlPj9Q4WbMT3TyE0rYQ-_bk-rZrpBEyW_EU4pJT4S1_T5Y3qjpdGwwaKbBEX_ctT4wE6t8rTB1q25ZVmSqKL-E4go15mUIE52iXTWsCcGt8Ex1Lt6ki6EY0JgI3xWK2aSWaUXPp2ltpHBEXIuVZ_6ZthUE6dztb2_VoWEq05eCNOYiJ03UAo0bUFHv5dtdmkyC4rS92_I8V1l3cHQWaSWWbSDCtCchxzgOz67lWHEj_hO98bCdQMB08ZArbuhj0Sogk-a-D8_ROKyE9o2gGzUit6DEo3LJtWc

abacatepay.url=https://api.abacatepay.com
abacatepay.token=abc_dev_TPFHZ5RCRxHdkJB2jkRJM4ep