spring.datasource.url=jdbc:h2:mem:compia
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

melhorenvio.token=${MELHORENVIO_TOKEN}

abacatepay.url=https://api.abacatepay.com
abacatepay.token=${ABACATEPAY_TOKEN}
